# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-scope" do
  name "git-scope"
  desc "Fast TUI dashboard for managing many Git repositories"
  homepage "https://github.com/echaouchna/git-scope"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-scope"

  on_macos do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_amd64.tar.gz"
      sha256 "feaafd626328886f70497a2b0ed31742ba31704ccd98d0e17bba21df83cf2610"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_arm64.tar.gz"
      sha256 "5183ad8423cfb50f551b5878ba9d8cb98b467d2d3b549cb156b0c5c9c5d71a6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_amd64.tar.gz"
      sha256 "e1beba0aed88b7f91c3604db4ffacd9014726db01d67c5abe393203825119076"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_arm64.tar.gz"
      sha256 "62062672ffc405b90ce07fa4945ef8567b5f20896162b9d5cf997da9d4d9035a"
    end
  end

  # No zap stanza required
end
