# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-scope-tip" do
  name "git-scope-tip"
  desc "Fast TUI dashboard for managing many Git repositories (tip)"
  homepage "https://github.com/echaouchna/git-scope"
  version "1.3.0-tip.50.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-scope"

  on_macos do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_amd64.tar.gz"
      sha256 "54dc579ff454ce38142f0f87683d9f40ae8ec115c16b2b3e5fc1216e50b66f86"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_arm64.tar.gz"
      sha256 "8b895afc7740e98e7849e52744f427828cf951ebfbca842ffcdf59def46ce562"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_amd64.tar.gz"
      sha256 "ba0a1dd66bc5ec58a5c2c0e5275f36241e98edbaa127cbe5d7936fde0393d462"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_arm64.tar.gz"
      sha256 "af14ca0aa89052ecfaac3f2933a303e9b89ccdecb3d05d7853aad3ab571bc25c"
    end
  end

  # No zap stanza required
end
