# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-scope-tip" do
  name "git-scope-tip"
  desc "Fast TUI dashboard for managing many Git repositories (tip)"
  homepage "https://github.com/echaouchna/git-scope"
  version "1.2.0-tip.26.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-scope"

  on_macos do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_amd64.tar.gz"
      sha256 "80cfdab562b42011fc22cab9022b6dcba32b8e5744a74e62d62887e8fc9f7e6f"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_arm64.tar.gz"
      sha256 "29c3104c8e401a261f4dd57d5dfb2b206e2fa3b5f08a811e486aea3dddfd43a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_amd64.tar.gz"
      sha256 "23615973201525ccf91f975cb9ce158e28b8e0588e39333a4133472979227972"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_arm64.tar.gz"
      sha256 "99132ecf2e7c9f8b92daba317961828f2ddda4914fff78c5ff6a5ce3c29ec1c5"
    end
  end

  # No zap stanza required
end
