# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-scope" do
  name "git-scope"
  desc "Fast TUI dashboard for managing many Git repositories"
  homepage "https://github.com/echaouchna/git-scope"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-scope"

  on_macos do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_amd64.tar.gz"
      sha256 "eff3c6439cf99379bb69ebc7e978faf20a89fedd53c37ed25bd8dcbe2998d0bd"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_darwin_arm64.tar.gz"
      sha256 "9b8650aaf38294e09fec8793378e511299bc5c3069319d4f459567c3a2f9c2b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_amd64.tar.gz"
      sha256 "b42c2eeac161a5264de0cecd3927ffafba80548fee591fcb4a26bc4db1281b78"
    end
    on_arm do
      url "https://github.com/echaouchna/git-scope/releases/download/v#{version}/git-scope_#{version}_linux_arm64.tar.gz"
      sha256 "7e65fc84ae561b1045b4e8597137699f295c351c52d4181da31b95dde0206e3d"
    end
  end

  # No zap stanza required
end
