# Generated by the release workflows of https://github.com/echaouchna/runway. Do not edit.
class RunwayEdge < Formula
  desc "Deploy applications to Google Cloud Run (development build of main)"
  homepage "https://runway.echaouchna.dev/"
  version "0.1.1-edge.12"
  license "Apache-2.0"

  livecheck do
    skip "Rebuilt on every push to main"
  end

  on_macos do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.12-aarch64-apple-darwin.tar.gz"
      sha256 "827765a7b76a7adee32f4d161c7d6db7f100562eca349f365f2c21e12de034b8"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.12-x86_64-apple-darwin.tar.gz"
      sha256 "5f30cee4739ca99a95a93af8b1d302c1069157fc220f6d83ef65939592af7dcf"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.12-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "fb96c39cb22067e6e7d61c503c6106f06d1bf72c2c75fbc460e274513a3aed0f"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.12-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a879dd270c9c22d25e1e99e0fd703c8faf7fab59210af9c9c7a2cbe50f86a855"
    end
  end

  def install
    bin.install "runway"
    generate_completions_from_executable(bin/"runway", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runway --version")
  end
end
