# Generated by the release workflows of https://github.com/echaouchna/runway. Do not edit.
class RunwayEdge < Formula
  desc "Deploy applications to Google Cloud Run (development build of main)"
  homepage "https://runway.echaouchna.dev/"
  version "0.1.1-edge.5"
  license "Apache-2.0"

  livecheck do
    skip "Rebuilt on every push to main"
  end

  on_macos do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.5-aarch64-apple-darwin.tar.gz"
      sha256 "73df8ba2fb1074ef5e9dc02551574a4ed01aadd8b351cd4d2a748bbe16a198b1"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.5-x86_64-apple-darwin.tar.gz"
      sha256 "3d5309ae6c0533c3369c7eda160691b078297e13566efb33ca3680d2560dc059"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b5aff12ed35a1acdf2bcea226fce6051c589163eb273f94c453ef2774e781057"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7990d858a9212a8f93eaafe3c50bf4bc8c7fdf17c412b3560d90f0fc68cb2c35"
    end
  end

  def install
    bin.install "runway"
    generate_completions_from_executable(bin/"runway", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runway --version")
  end
end
