# Generated by the release workflows of https://github.com/echaouchna/runway. Do not edit.
class Runway < Formula
  desc "Deploy applications to Google Cloud Run from a single runway.yaml"
  homepage "https://echaouchna.github.io/runway/"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.1/runway-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "a22b465af7bba3c3247f2fa0b272501ffb0f98eb04b0e65e723aca319dd20b7d"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.1/runway-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "02c95afab82bbe50b201b4550cc5d818f9ed4bea371c8261071458f23c7eec12"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.1/runway-v0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4981435583f549670eb008c7e36c631cf37e47181e49bf902027921c0bbde462"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.1/runway-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f1d585c1aa602d628c93f6f0f8f1f5db6d08639b2581f6f9dfc21e0dfe79f1d4"
    end
  end

  def install
    bin.install "runway"
    generate_completions_from_executable(bin/"runway", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runway --version")
  end
end
