# Generated by the release workflows of https://github.com/echaouchna/runway. Do not edit.
class RunwayEdge < Formula
  desc "Deploy applications to Google Cloud Run (development build of main)"
  homepage "https://runway.echaouchna.dev/"
  version "0.1.1-edge.8"
  license "Apache-2.0"

  livecheck do
    skip "Rebuilt on every push to main"
  end

  on_macos do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.8-aarch64-apple-darwin.tar.gz"
      sha256 "0bd8616fae9705dbc671db6e536dc800b5c0c036fd1d3543825b9a73b2daf0f3"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.8-x86_64-apple-darwin.tar.gz"
      sha256 "4414560f9150b2e59c57a80449040d555b72cc1bd61721903430f14723f894d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.8-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bbb2a99980e37ff8c1e669551023801886eb4d4f7ed52e6633636db6de549933"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/edge/runway-v0.1.1-edge.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9cd12592d04bd32123462051736cfa5821122e44fe2c8c18062618c401fcc444"
    end
  end

  def install
    bin.install "runway"
    generate_completions_from_executable(bin/"runway", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runway --version")
  end
end
