# Generated by the release workflows of https://github.com/echaouchna/runway. Do not edit.
class Runway < Formula
  desc "Deploy applications to Google Cloud Run from a single runway.yaml"
  homepage "https://echaouchna.github.io/runway/"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.0/runway-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "cabee0351401b1a0869616e1d14e0861b9ea9ac420740703a1679611183b758d"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.0/runway-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "80698ec3d5a74aa12b7638a5c3be40c5a4a6974e05a37e3459987446193d84d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.0/runway-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "25d13926a44dd95a51a61219b65fee4600dc8898b93328a75872123712dafa09"
    end
    on_intel do
      url "https://github.com/echaouchna/runway/releases/download/v0.1.0/runway-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e9688ed25dc500334e8b6167f838752fc82800d7f336767150765a604b4f5991"
    end
  end

  def install
    bin.install "runway"
    generate_completions_from_executable(bin/"runway", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runway --version")
  end
end
